services:
  - type: web
    name: amcb-frontend
    env: node
    plan: free
    buildCommand: npm run install-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
