services:
  - type: web
    name: amcb-frontend
    env: static
    plan: free
    buildCommand: npm run install-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
